### ISSUE TITLE
When migrating to MySQL > "BLOB/TEXT column 'question' used in key specification without a key length"

### ISSUE THREAD

**Issue by roperi** [pinax/pinax-waitinglist#19]
I installed Stripe using project starter. Later on I added Cohorts and Waitinglist. 

Anyway, I decided to change database engine from SQLite to MySQL using mysqlclient. 

```
DATABASES = {
    "sqlite": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": "dev.db",
    },
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASS'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
    }
```

Then, when attempting to migrate, this happened (note that it breaks at waitlinglist):
```
(venv) $ python manage.py migrate
Operations to perform:
  Apply all migrations: account, eventlog, sessions, admin, sites, auth, pinax_cohorts, contenttypes, pinax_stripe, pinax_waitinglist
Running migrations:
  Rendering model states... DONE
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying account.0001_initial... OK
  Applying account.0002_fix_str... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying eventlog.0001_initial... OK
  Applying eventlog.0002_auto_20150113_1450... OK
  Applying eventlog.0003_auto_20160111_0208... OK
  Applying pinax_cohorts.0001_initial... OK
  Applying pinax_stripe.0001_initial... OK
  Applying pinax_stripe.0002_auto_20151205_1451... OK
  Applying pinax_stripe.0003_make_cvc_check_blankable... OK
  Applying pinax_waitinglist.0001_initial...Traceback (most recent call last):
File "./manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 359, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 322, in alter_unique_together
    self.execute(self._create_unique_sql(model, columns))
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/home/user/.virtualenvs/pinax/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 42, in defaulterrorhandler
    raise errorvalue
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'question' used in key specification without a key length")
```

According to Django developers [it's a MySQL problem](https://code.djangoproject.com/ticket/2495).

**Comment by roperi** [comment]
More on this:

[MySQL error: key specification without a key length](http://stackoverflow.com/questions/1827063/mysql-error-key-specification-without-a-key-length)	

> The error happens because MySQL can index only the first N chars of a BLOB or TEXT column. So The error mainly happen when there is a field/column type of TEXT or BLOB or those belongs to TEXT or BLOB types such as TINYBLOB, MEDIUMBLOB, LONGBLOB, TINYTEXT, MEDIUMTEXT, and LONGTEXT that you try to make as primary key or index. With full BLOB or TEXT without the length value, MySQL is unable to guarantee the uniqueness of the column as it’s of variable and dynamic size. So, when using BLOB or TEXT types as index, the value of N must be supplied so that MySQL can determine the key length. However, MySQL doesn’t support a key length limit on TEXT or BLOB. TEXT(88) simply won’t work....
> ...
> The solution to the problem is to remove the TEXT or BLOB column from the index or unique constraint, or set another field as primary key. If you can’t do that, and wanting to place a limit on the TEXT or BLOB column, try to use VARCHAR type and place a limit of length on it. By default, VARCHAR is limited to a maximum of 255 characters and its limit must be specified implicitly within a bracket right after its declaration, i.e VARCHAR(200) will limit it to 200 characters long only.

**Comment by roperi** [comment]
I put a print inside the BaseDatabaseSchemaEditor class in (django/db/backends/base/schema.py) to pinpoint which SQL statements fails whilst running `./manage.py mirgate`. This is where it breaks:

```ALTER TABLE `pinax_waitinglist_surveyinstance` ADD COLUMN `entry_id` integer NOT NULL UNIQUE
ALTER TABLE `pinax_waitinglist_surveyinstance` ALTER COLUMN `entry_id` DROP DEFAULT
ALTER TABLE `pinax_waitinglist_surveyinstance` ADD COLUMN `survey_id` integer NOT NULL
ALTER TABLE `pinax_waitinglist_surveyinstance` ALTER COLUMN `survey_id` DROP DEFAULT
ALTER TABLE `pinax_waitinglist_surveyanswer` ADD COLUMN `instance_id` integer NOT NULL
ALTER TABLE `pinax_waitinglist_surveyanswer` ALTER COLUMN `instance_id` DROP DEFAULT
ALTER TABLE `pinax_waitinglist_surveyanswer` ADD COLUMN `question_id` integer NOT NULL
ALTER TABLE `pinax_waitinglist_surveyanswer` ALTER COLUMN `question_id` DROP DEFAULT
ALTER TABLE `pinax_waitinglist_surveyquestion` ADD CONSTRAINT `pinax_waitinglist_surveyquestion_survey_id_c4585dd3_uniq` UNIQUE (`survey_id`, `question`)
...
django.db.utils.OperationalError: (1170, "BLOB/TEXT column 'question' used in key specification without a key length")```

**Comment by roperi** [comment]
I solved this editing the pinax/waitinglist/models.py (from `question = models.TextField() `to `question = models.CharField(max_length=200)`), deleting pinax/waitinglist/migrations/0001_initial.py and rerunning `makemigrations` and `migrate` again.  

I'm not 100% sure I should close this issue but I'm going to do it anyway as I feel it is a MySQL limitation and not a Pinax problem.
